### ISSUE TITLE
Replacement for "set_default_value"?

### ISSUE THREAD

**Issue by jankatins** [ipython/traitlets#106]
In knitpy, I use `set_Default_value` to reset (parts of) a traitlet based object to a known state. Unfortunately, this doesn't work anymore with the new standalone version of traitlets (after https://github.com/ipython/traitlets/pull/26):

``` python
    def execution_finished(self):
        self.output.flush()
        reset_needed = ["engine", "mode"
                        "chunk_label", "comment",
                        "include", "echo",  "include", "results"]
        for name in self.trait_names():
            if name in reset_needed:
                self.traits()[name].set_default_value(self)
```

-> https://github.com/JanSchulz/knitpy/blob/master/knitpy/knitpy.py#L853

What is the suggested way to "reset" a trait?

**Comment by JanSchulz** [comment]
I've now change that to:

```
        for name in self.trait_names():
            if name in reset_needed:
                try:
                    self.traits()[name].instance_init(self)
                except AttributeError:
                    # older ipython versions
                    self.traits()[name].set_default_value(self)
```

It feels a bit strage to call instance_init again, but setting the `setattr(self, name, self.traits()[name].default_value)` was resulting in some problems with Sentinel values.

**Comment by rmorshea** [comment]
@janschulz, sorry this has taken so long to get around to.

I'm assume the reason you are (or were) having problems is because notifications are being fired when you use `setattr`. Given that, there really isn't a good public API for silent setting with Traitlets. So for now your best bet really is to use `instance_init`.

For a while the idea of a context manager called `mute_trait_notifications` (as opposed to `hold_trait_notifications`) was being considered, but it wasn't particularly popular. If silent setting in Traitlets is something you'd value, we could reopen that discussion.

**Comment by rmorshea** [comment]
@jankatins, this may feel a bit hacky, but you can actually restore the default values like this:

```python
class MyClass(HasTraits):
    i = Int()
    d = Dict()

mc = MyClass()
mc.i = 2
mc.d = {"a": 1}
# no we clear trait values
mc._trait_values.clear()
assert mc.i == 0
assert mc.d == {}
```

**Comment by jankatins** [comment]
Thanks!
