### ISSUE TITLE
Documentation For Specifying Container Arguments

### ISSUE THREAD

**Issue by Lull3rSkat3r** [ipython/traitlets#180]
I have searched the docs, examples, and tests for an example of specifying a container type as a command line argument. Since I found nothing, I am assuming it is not supported at the moment. In particular I am trying to get a set of values as an argument. I tried the following:

```
myapp --containerarg={'A', 'B', 'C'}
myapp --containerarg=Set({'A', 'B', 'C'})
myapp --containerarg=['A', 'B', 'C']
myapp --containerarg='A' --containerarg='B' --containerarg='C'
```

**Comment by Carreau** [comment]
IIRC, you'll have to quote each:

`myapp --Class.containerarg="{'A', 'B', 'C'}"` But it might depend on the shell and other things.

**Comment by Lull3rSkat3r** [comment]
Works as expected. Might be worth documenting somewhere to help future users.

**Comment by minrk** [comment]
I've hesitated to document container traitlets on the command-line, since it's so unpleasant it's practically not supported. The gist is: A string that will be eval'd.

It's this way because we originally parsed the command-line before knowing anything about the classes to be configured. This is still true *in general*, but to generate the help, we populate a list of known configurable classes for each Application. With this information, we could conceivably populate proper argparse constructs for container traitlets (and everything else, for that matter) of classes in the known-configurables list.

**Comment by ankostis** [comment]
I agree the current situation with containers is unpleasant.

If you plan to correct it, I want to give an example of some notorious programs (java interpreter) that accept an arbitrary number of flags with constructs like that:

    java -Dfoo=1  -D bar=12 ...

I really miss this from *traitlets* so far. 
So I suppose by utilizing the list of known configurables, *argparse* `action='append'` behavior like above might be possible for containers, correct?
An alternative would be to use `argparse.add_args(nargs='*')` for list-traits.

Would a PR like this be in the right direction?
Or are you thinking to enhance flags/aliases somehow for achieving this?

**Comment by ankostis** [comment]
@minrk any opinions on scanning all conf-classes to collect container-traits and append any matching aliases into `ArgParseConfigLoader` either with `action='append'` or `nargs='*'`?

**Comment by minrk** [comment]
I'm a bit torn on doing it for flags/aliases, or for everything. I might lean ever so slightly toward just the flags & aliases, but the implementation may make it easier to apply to everything. I think we should do it, though.

**Comment by ankostis** [comment]
Let's start with the aliases-only, where *argparse* lib is already used (for flags this proposal does not make sense).

I'm drafting a plan, to see if I have a solid understanding:

1. The `ArgParseConfigLoader` constructor needs at first the list of user-specified configurable classes;
2. Then the loader it has to collect all `HasTraits` classes and subclasses from this list using the `Application._classes_in_config_sample()` (so it has to become an independent function in `application.py`);
3. For every alias, modify the `KVArgParseConfigLoader._add_arguments()` to search first in the collected classes if they contain a container-trait, and if so, to append it into `ArgumentParser` either as:
   1. `add_argument(..., action='append')`, or
   2. `add_argument(..., nargs='*')`.
   3. have a metadata on the trait specifying in which way to treat argparse.
4. Modify `KVArgParseConfigLoader._convert_to_config()` to handle args with list-of-values.

Is my understanding correct?  

For step 3, I prefer (3.1) to be the default, because it might be easier to evaluate values per-item.

An example of the cmd-line would be like that:

    foocmd   --alias1=1  --alias1=ab --alias`='["dfffg", 3]'   --alias2 a 2 c

and the collected config tuples/list (depending on the trait) to be

- alias1: `(1, "ab", ["dfffg", 3])`
- alias2: `("a", "b", "c")`


I would love to see expand the above spec for populating also `Dict` traits:

    foocmd   -D key1=v1 -D key2=2

**Comment by minrk** [comment]
I think you've roughly got it, but nothing should need to be pushed to a top-level function. You should be able to pass `self.classes` from the Application to the Loader's constructor.

**Comment by ankostis** [comment]
> You should be able to pass self.classes from the Application to the Loader's constructor.

You mean the list of all configurables (and any subclasses) involved, derived from `self.classes`, correct?
(see the discussion on #289).
Yes, you are right, the `Application` can prepare this list by invoking `_classes_in_config_sample()` on it self.

**Comment by ankostis** [comment]
There is a slight complication when configurable *subclasses* are involved for container traits.
I can explain with the following sample code (writing it from memory, excuse any errors):

```
class Base(HasTraits): 
    a = List([])

class Sub(Base): 
  pass

class Cmd(Application):
    classes = [Sub]  ## Note on #289: frequently list given like that.
```

Then, in command-line it should be possible to enter all 3 commands:

```
cmd  --Base.a=1 --Base.a=2  ## Base.a = [1, 2]
cmd  --Sub.a=1  --Sub.a=2   ## Sub.a = [1, 2]
cmd  --Base.a=1  --Sub.a=2  ## ?? Base.a = [1], Sub.a = [1, 2] ??
```

The first 2 cases, are "easy", but how to handle the last one?
What should be the resultant `Base` and `Sub` configurables?

**Comment by minrk** [comment]
I would say that Sub.a trumps Base.a, so you get Base.a = [1], Sub.a = [2] in the latter case (don't try to merge across subclasses). I don't expect this to come up, and we can guarantee that it doesn't come up if we only enable this for aliases.

**Comment by ankostis** [comment]
Check for alternative syntax in #180.
