### ISSUE TITLE
[question] Could `@observe` take a traitlets instance ? 

### ISSUE THREAD

**Issue by Carreau** [ipython/traitlets#225]
Right now it takes a name, but could we do:

```
class C(HasTrait):

   foo = FooTrait():
   
   @observe(foo):
   def _(...):
         ...
```

and extract the name from the foo instance instead of requiring a string ? 

There is probably a reason **not** to do that, but just wondering why.

**Comment by minrk** [comment]
I don't believe the name is available from the instance while in the class-constructing scope. If it were, we could have a really nice:

```python
foo = Trait()
@foo.observe
def _(...)
```

Properties do this, so it might be possible, but it also might rely on the fact that @property` decorates a function, which has a name, unlike an instance.

**Comment by SylvainCorlay** [comment]
It also takes multiple names as pargs..

**Comment by rmorshea** [comment]
The name is available during class-construction, however this is only true as long as the trait and observe method are defined on the same class. This means you'd still want a string based api when subclassing, and personally I think it'd be better to stick to a single api, rather than supporting many.

As far as `@property` goes, the reason you need to maintain the same name across functions is because the `getter` and `setter` wrapper methods of a property actually return a new property instance. Thus forcing users to keep everything about the property confined to a single name. In our case though, because of the way the descriptors are initialized, defining traits, observers, and validators under different names is really the only way to go.

**Comment by Carreau** [comment]
Fair enough, to not complicate the API. Though would argue that putting code in string tend to easily hide bugs as you can easily have a typo that can get unnoticed. 

Feel free to close.

**Comment by rmorshea** [comment]
@Carreau we could check that the names given to `@observe` are traits of the given class in `class_init`.

**Comment by Carreau** [comment]
> @Carreau we could check that the names given to @observe are traits of the given class in class_init.

Possible, I'm more thinking also as linter while you are coding. But traitlets in general are too dynamic for that. 

Let's keep the current API, but keep this kind of things in mind just in case.
