### ISSUE TITLE
Union trait does not handle trait metadata correctly

### ISSUE THREAD

**Issue by rmenegaux** [ipython/traitlets#244]
If I have a `HasTraits` class, called `Mix`, that has a `Union` trait, called `union`, then since the trait metadata of `union` is a class attribute, all `Mix` instances will have the same metadata for `union`, regardless of the actual trait type of `union`.

This can be harmful if you have a `Union` of traits with different `to_json` for example.

I hope this will be clearer with an example:
```python
from traitlets import Float, Unicode, HasTraits

class Mix(HasTraits):
    union = Float().tag(metadata="I'm a float") | Unicode().tag(metadata="I'm still a float, but with unicode metadata")
    
mix1 = Mix(union=0)
print mix1.union, mix1.trait_metadata('union', 'metadata')
mix2 = Mix(union='')
print mix1.union, mix1.trait_metadata('union', 'metadata')
```
outputs
```python
0.0 I'm a float
0.0 I'm still a float, but with unicode metadata
```

**Comment by SylvainCorlay** [comment]
Really good catch, this is serious.

**Comment by SylvainCorlay** [comment]
We should change the logic so that the meta data of a Union would be a `property` which fetches the metadata of the first type of the list for which the value passes validation.

**Comment by SylvainCorlay** [comment]
Or just have top-level metadata for the Union itself, and remove the setting of the metadata.

**Comment by rmorshea** [comment]
Additionally, any metadata added via `Union.tag` is lost altogether whenever a value is set.

As you said @SylvainCorlay, union traits really ought to have static, and top-level metadata because you have to go through a `HasTraits` class, not an instance, to gain access to it. The kind of value-dependant metadata talked about here would only make sense if it were being accessed through a `HasTraits` instance. Thus, `HasTraits.trait_metadata` is the place for this logic.

**Comment by SylvainCorlay** [comment]
@rmenegaux has work in progress to fix this in a backward compatible way. I let him open the PR.
