### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by gvanrossum** [ipython/traitlets#270]
I tried to understand what this library does but all docs pointers seem to focus on advanced usages, and the README focuses on installation. What does simple use of this library actually look like? If the answer is "it's just like traits" that doesn't help me at all, I have no idea what that does either. (Or at least today I'm wearing the hat where I'm pretending not to. ;-)

**Comment by SylvainCorlay** [comment]
@gvanrossum thanks for your interest!

We can certainly do better on narrative documentation. Would you be interested in us expanding on specific points here? (On the subject of PEP 487?)

**Comment by gvanrossum** [comment]
I was just hoping for a tutorial that shows off a bunch of the common (simple) use cases. Is there really nothing you have for that? Not even a blog post somewhere? Then how do people get up to speed on using traitlets?

I'm not sure what you meant by the PEP 487 reference.

**Comment by minrk** [comment]
For a long time, and until very recently, traitlets was just an internal utility as part of IPython, not meant for use outside the project. We split it off as part as a standalone package, but haven't managed to build up the documentation that a standalone package deserves.

For now, the closest approximation of a tutorial is [this documentation](http://traitlets.readthedocs.io/en/stable/using_traitlets.html) which goes through the basics of inheriting from HasTraits, defining a few traits and callbacks.

**Comment by SylvainCorlay** [comment]
I mentioned the PEP 487 because traitlets were mentioned in the context of the discussion of this PEP.

Regarding existing tutorials, we have some material on [readthedocs](http://traitlets.readthedocs.io/en/latest/using_traitlets.html).

In short, traitlets let the user define classes that have
 1. Attributes (traits) with type checking and dynamically computed default values
 2. Traits emit change events when attributes are modified
 3. Traitlets perform some validation and allow coercion of new trait values on assignment. They also allow the user to define custom validation logic for attributes based on the value of other attributes.

Finally, the base `HasDescriptors` metaclass allows users to define other descriptors than trait types, without having to write metaclass code.  (We have used it to make a toy signals and slot library, where signature of slots are described with trait types). This is where traitlets are related with PEP 487 which should allow such usecases without any metaclass. (Besides, the main example provided in the PEP is a traits library.)

### Traitlets Usage

 - Attributes with type checking and default values

```python
import getpass

class Identity(HasTraits):
    username = Unicode()

    @default('username')
    def _default_username(self):
        return getpass.getuser()
```

```python
class Foo(HasTraits):
    bar = Int()

foo = Foo(bar='3')  # raises a TraitError
```
```
TraitError: The 'bar' trait of a Foo instance must be an int,
but a value of '3' <class 'str'> was specified
```

 - traitlets implement the observer pattern

```python
class Foo(HasTraits):
    bar = Int()
    baz = Unicode()

foo = Foo()

def func(change):
    print(change['old'])
    print(change['new'])   # as of traitlets 4.3, one should be able to
                           # write print(change.new) instead

foo.observe(func, names=['bar'])
foo.bar = 1  # prints '0\n 1'
foo.baz = 'abc'  # prints nothing
```

When observers are methods of the class, a decorator syntax can be used.

```python
class Foo(HasTraits):
    bar = Int()
    baz = Unicode()

    @observe('bar')
    def _observe_bar(self, change):
        print(change['old'])
        print(change['new'])
```

 - Custom validation logic on trait classes

```python
from traitlets import HasTraits, TraitError, Int, Bool, validate

class Parity(HasTraits):
    value = Int()
    parity = Int()

    @validate('value')
    def _valid_value(self, proposal):
        if proposal['value'] % 2 != self.parity:
            raise TraitError('value and parity should be consistent')
        return proposal['value']

    @validate('parity')
    def _valid_parity(self, proposal):
        parity = proposal['value']
        if parity not in [0, 1]:
            raise TraitError('parity should be 0 or 1')
        if self.value % 2 != parity:
            raise TraitError('value and parity should be consistent')
        return proposal['value']

parity_check = Parity(value=2)

# Changing required parity and value together while holding cross validation
with parity_check.hold_trait_notifications():
    parity_check.value = 1
    parity_check.parity = 1
```

In the case where the a validation error occurs when `hold_trait_notifications` context manager is released, changes are rolled back to the initial state.

 - Finally, trait type can have other events than trait changes. This capability was added so as to enable notifications on change of values in container classes. The items available in the dictionary passed to the observer registered with `observe` depends on the event type.

### Usage in Project Jupyter

We mostly use traitlets for
 - configuration of applications like the jupyter notebook server
 - in the jupyter interactive widgets library to describe models for UI components.

**Comment by gvanrossum** [comment]
I wasn't aware that traitlets were mentioned in the PEP 487 docs -- i found
a reference to it in some other context.

The readthedocs page you link to was what drove me to post this issue,
since that page starts out with advanced usage. Honestly it looks like it
was generated from your docstrings -- that's usually not good for a
tutorial and even for reference docs it's hard to get good quality docs
that way. The text you posted after that would serve as a great tutorial --
is that also on readthedocs? It should!

**Comment by minrk** [comment]
@SylvainCorlay thanks! I opened #272 splitting the using_traitlets doc into separate tutorial and API reference pages, where it was interleaved before, making the new using_traitlets basically your comment above. I think there's a lot more to add on the tutorial side, but it's a good starting point.

Thanks for the pointers, @gvanrossum!

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one, since @minrk's #272 at least addressed the most basic tutorial that @SylvainCorlay provided as a comment here. Go team!

Thanks everyone and happy hacking! :bowtie:
