### ISSUE TITLE
Default value for Union?

### ISSUE THREAD

**Issue by pbugnion** [ipython/traitlets#271]
The `Union` trait does not support setting a default value explicitly:

```python
class A(HasTraits):
    trait = Union([Int(), Float()], default_value=20)

print(A().trait) # => 0
```

The workaround is to specify the appropriate default value for the first trait in the union:

```python
class A(HasTraits):
    trait = Union([Int(default_value=20), Float()])

print(A().trait) # => 20
```

Is this intentional? Unless I'm missing something, a possible workaround would be to replace this line (currently line 1789) in the source code:

```python 
self.default_value = self.trait_types[0].default_value
```

... with something that checks whether a default value was passed in through the constructor. 

I'll happily put in a PR if that's the case.

**Comment by SylvainCorlay** [comment]
This was intentional, but I don't have a strong opinion on this. However, there is a subtle issue with `Union` default value that will find a PR when I am back from my travels #244

**Comment by SylvainCorlay** [comment]
@pbugnion I was working on some changes in Union. What do you think the most meaningful behavior would be.
 - pick the first default_value not to be Undefined in the traits and if all are undefined and then default to the one of the union
 - pick the one of the union if not Undefined and then default to the first not to be undefined in the traits?

In terms of metadata, #274 makes it so that the metadata of the current value has priority.

**Comment by pbugnion** [comment]
That's great! I tend to think the latter (letting someone override the default values of the individual traitlets with the union default value) makes more intuitive sense, but I don't have strong opinions either way.

I think what really threw me here was that the docstring wasn't very explicit about how to set the default value.
