### ISSUE TITLE
Configurable validates too often

### ISSUE THREAD

**Issue by jasongrout** [ipython/traitlets#390]
Consider this:

```python
from traitlets.config import Configurable
class A(Configurable):
    x = Int(1)
    
    @validate('x')
    def f(self, proposal):
        print('validate x')
        return proposal.value
A(x=5)
``` 
prints:
```
validate x
validate x
```

while this:

```python
from traitlets import HasTraits
class A(HasTraits):
    x = Int(1)

    @validate('x')
    def f(self, proposal):
        print('validate x')
        return proposal.value
A(x=5)
```
only validates x once:
```
validate x
```
For some reason, Configurable is validating x twice, but HasTraits is only validating once.

**Comment by rmorshea** [comment]
This is a special case in the configurable constructor where trait assignments are explicitly done twice in order to override any values that may have been set by a classes' config. This could be resolved by moving config assignment and loading from `Configurable.__init__` to `Configurable.setup_instance` which occurs prior to `__init__`.

**Comment by rmorshea** [comment]
It's actually easier than that. The second call was required due to the timing of calls to descriptor initialization via `instance_init`. Originally descriptors were setup in `__init__`, but now they occur in `__new__`, thus we can remove the redundant `setattr` in `Configurable.__init__` and simply use `super().__init__(**kwargs)` instead.

See #391
