### ISSUE TITLE
Any() trait not validated

### ISSUE THREAD

**Issue by jasongrout** [ipython/traitlets#428]
I'm seeing the following in traitlets 4.3.2. It appears that the validation for `x` is not getting called. If I change `x = Any(())` to `x = Tuple( () )`, the validator is called.

```
In [2]: from traitlets import HasTraits, Unicode, Any, validate, Tuple
   ...: class A(HasTraits):
   ...:     x = Any(())
   ...:     
   ...:     @validate('x')
   ...:     def f(self, proposal):
   ...:         print(proposal)
   ...:         return (1,2)
   ...: A().x
   ...: 
Out[2]: ()

In [3]: import traitlets
   ...: traitlets.__version__
   ...: 
Out[3]: '4.3.2'
```

**Comment by minrk** [comment]
This is the general "default values are not cross-validated" issue. Default values are cross-validated in master ( #332), but in a way that causes infinite recursion if there are reference cycles in cross-validators. I'll see if I can fix the cycle without removing cross-validation of defaults altogether.

**Comment by minrk** [comment]
Due to the problems encountered by cross-validating defaults seen in master, I think it's probably safest to close this as 'wontfix'. Default values are not cross-validated. We can consider coming back to it, but as mentioned in #434, the same can always be accomplished on an opt-in basis with a `@default` method that triggers the same validation logic.
