### ISSUE TITLE
globally disable validation

### ISSUE THREAD

**Issue by satra** [ipython/traitlets#507]
is there a way to globally disable validation? this is not necessary to implement. i'm just checking if this is possible.

**Comment by rmorshea** [comment]
There is not. Why do you need to disable it?

**Comment by satra** [comment]
thank you @rmorshea. mostly for performance reasons (e.g., stats on a filesystem for file existence, especially in a graph flow, where multiple objects are read by different processes). each time i pickle and unpickle a hastraits, it will perform validation. if i'm confident about some chain of my process, it would be nice if the validation happened ones in the chain, rather than every single time.

**Comment by rmorshea** [comment]
Since validation doesn’t go through any global bottleneck there isn’t a
straightforward way to accomplish this.

Notifications on the other hand do go though a global bottleneck. There
still isn’t a way to “mute” notifications, but considering that there is a
way to “hold” them with `HasTraits.hold_trait_notifications` it seems like
might be relatively straightforward to shift validation into `@observe` and
implement your own `mute_trait_notifications`.

**Comment by satra** [comment]
thank you @rmorshea 

will keep that in mind.
