### ISSUE TITLE
Allow default_value to Instance

### ISSUE THREAD

**Issue by krey** [ipython/traitlets#518]
I would like to have a trait that is a pandas dataframe:

```python
from traitlets import HasTraits, Instance
import pandas as pd

class Test(HasTraits):
    foo = Instance(pd.DataFrame, kw={'columns': ['int_col', 'float_col'], 'dtype': float})

test = Test()
```

Unfortunately, the constructor `pd.DataFrame` does not have a dtypes argument where I could specify the datatypes by column. (This issue is old enough to go to school now https://github.com/pandas-dev/pandas/issues/4464)

```python
>> print(test.foo.dtypes)
int_col      float64
float_col    float64
dtype: object
```

And the only way to initialize it properly is:
```python
>> test.foo = pd.DataFrame(columns=['int_col', 'float_col']).astype({'int_col': int, 'float_col': float})
>> print(test.foo.dtypes)
int_col        int64
float_col    float64
dtype: object
```

**Comment by rmorshea** [comment]
Does the `@default` decorator suite your needs?

https://traitlets.readthedocs.io/en/stable/using_traitlets.html#default-values-and-checking-type-and-value

**Comment by krey** [comment]
Thanks @rmorshea 

It's a workaround for sure, but morally it should be part of the trait, not the class, no?

**Comment by rmorshea** [comment]
Unfortunately no. Default values that are declared without `@default` are basically like class attributes. The problem with class attributes is that they are shared among all their instances. We can demonstrate an analogous problem with the following **valid** code:

```python
class A:
    lst = []

a_1st = A()
a_1.lst.append(1)

a_2 = A()
assert a_2.lst == [1]
```

We might expect to `assert a_2.lst == []` but because `lst` is a class attribute both `a_1` and `a_2` share the same list. If it were possible to declare:

```python
class A(HasTraits):
    lst = List(default=[])
```

You'd encounter a similar problem.

Forcing you to use `@default` may not be semantically pretty, but it is functionally correct.
