### ISSUE TITLE
Dict does not set .default_value

### ISSUE THREAD

**Issue by DeepHorizons** [ipython/traitlets#579]
Ran into a problem where I was getting `traitlets.Undefined` popping up. Debugging it `.default_value` is never being set. It is being passed as an argument to the init of the super class `Instance`. There is a note in the docstring that talks about making a copy of `default_value`, but oddly enough looking at when the docstring was added (eb6deb41efa5ecac05617ed3c344f4dc50c4b883) it doesn't seem to update `.default_value` either.

```
class Test(traitlets.HasTraits):
    a = traitlets.Dict(default_value={'a':1}).tag(config=True)
    b = traitlets.Int(default_value=5).tag(config=True)

Test.a.default_value
Test.b.default_value
```

**Comment by rmorshea** [comment]
This is because dictionaries are mutable data types and must be re-constructed for each new instance that requests a default value. On master (see [here](https://github.com/ipython/traitlets/issues/401 for release updates), the solution to this is a actually to use [`HasTraits.trait_defaults()`](https://github.com/ipython/traitlets/blob/1d274419f0f3ae452df12caeadfd2891fc926f61/traitlets/traitlets.py#L1542) to request default values since this will be able to retrieve dynamic default values that may have been created by any `@default` methods.

**Comment by rmorshea** [comment]
I'm going to close this since the mutable nature of dicts doesn't lend them to having a `Dict.default_value` attribute. With that said, the `HasTraits.trait_defaults` (unreleased as of today) will address your needs. Keep up with #401 for updates on a future release including the aforementioned method.
