### ISSUE TITLE
Setting Byte image data from TypeScript

### ISSUE THREAD

**Issue by cabreraalex** [ipython/traitlets#583]
I am writing a ipywidget that sends image data back and forth between the kernel and javascript frontend.

While sending data to the frontend works, setting the model from the front-end fails silently. This is the call:

```typescript
        blb.arrayBuffer().then((arr: ArrayBuffer) => {
          this.model.set("counterData", Array.from(new Uint8Array(arr)));
          this.model.save_changes();
```

In contrast when I set the array to be a simple array it works perfectly:
```typescript
        blb.arrayBuffer().then((arr: ArrayBuffer) => {
          this.model.set("counterData", [1, 2, 3]);
          this.model.save_changes();
```

Any thoughts on this issue or how to debug it?

**Comment by rmorshea** [comment]
You should probably post to https://github.com/jupyter-widgets/ipywidgets/issues instead. My best guess is that this has something to do with serialization since it looks like `Uint8Array` serializes to an object rather than an array. Perhaps that's causing an error server-side if you're expecting a list?

```javascript 
JSON.stringify(Uint8Array.from([1, 2, 3])) === {"0": 1, "1": 2, "2": 3}
```

If you're using `Uint8Array` to type check something then maybe just cast using `Array.from(...)` before sending the data over?

Even if this fixes your problem, you should still post an issue since this shouldn't fail "silently".

**Comment by cabreraalex** [comment]
Good idea, thanks for the thorough response!
