### ISSUE TITLE
Removing traits

### ISSUE THREAD

**Issue by jvail** [ipython/traitlets#585]
I am using "add_traits" to dynamically add traits to my class. I was wondering what the recommended way of removing a trait is. A "remove_trait" method does not exist, it seems.

Thank you
Jan

**Comment by rmorshea** [comment]
So my first suggestion is to reconsider whether you actually need to dynamically add traits to solve your problem, because dynamically adding traits is already a "hack" of sorts. Under the hood it actually creates a whole new class, which is quite expensive in Python even if you aren't using metaclasses (which `traitlets` does) and assigns it to the instance. You can test this with the following code:

```python
ht = HasTraits()
assert HasTraits is ht.__class__
ht.add_traits(dynamically_added_trait=...)
assert HasTraits is not ht.__class__
```

However... if you absolutely need to delete a dynamically added trait, you can actually just delete the trait from `ht.__class__` because its unique to the instance:

```python
del ht.__class__.my_dynamically_added_trait
```

Given all this, I don't think we'd implement a `remove_trait` method unless there was a demonstrable need for it, and even then I'm not sure we would, if only to discourage the use of `add_traits`.

**Comment by jvail** [comment]
Ok, thank you for the clear answer and explanation.
