### ISSUE TITLE
5.0.0 fails to parse args

### ISSUE THREAD

**Issue by POD666** [ipython/traitlets#608]
Hi, 
Looks like you are about to release `5.0.0` but it already gets fetched by `jupyter` :
```shell
docker run --rm -it python:3.7 bash
$ pip install jupyter
...
Collecting traitlets>=4.2
  Downloading traitlets-5.0.0-py3-none-any.whl (97 kB)
...
```
And leads to an exception in my tests, you may try to reproduce with:
```
$ python
>> from nbconvert import nbconvertapp
>> nbconvertapp.main(["nbconvert", "--output", "/tmp/qwe.txt", "simple-py36.ipynb"])
...
: error: unrecognized arguments: simple-py36.ipynb
...
```
I have fixed it by pinning to `traitlets>=4.2,<5.0.0`.

**Comment by IanMatthewHuff** [comment]
I believe this is the same issue hitting VSCode currently. We pass command line arguments to ipykernel to start it with a specific configuration. We install newest ipykernel in environments for our customers and just last night every fresh environment broke for customers:
https://github.com/microsoft/vscode-python/issues/13701
I didn't see this issue yet, but by process of elimination it was found that downgrading traitlets to 4.3.3 fixed the issue.

**Comment by blink1073** [comment]
Tracking this down, it looks like we no longer allow passing the name of the subcommand as the first arg to `launch_instance`.  The following works with `traitlets 5.0.0`:

```python
>>> from nbconvert import nbconvertapp
>>> nbconvertapp.main(["--output", "hi", "Untitled.ipynb"])
[NbConvertApp] Converting notebook Untitled.ipynb to html
[NbConvertApp] Writing 272313 bytes to hi.html
```

**Comment by blink1073** [comment]
Interestingly, it was a warning in traitlets 4:

```
>>> from nbconvert import nbconvertapp
>>> nbconvertapp.main(["nbconvert", "--output", "hi", "Untitled.ipynb"])
[NbConvertApp] WARNING | pattern 'nbconvert' matched no files
[NbConvertApp] Converting notebook Untitled.ipynb to html
[NbConvertApp] Writing 272313 bytes to hi.html
```

**Comment by blink1073** [comment]
It looks like it used to treat that leading value as an `extra_arg`, but no longer does

**Comment by minrk** [comment]
@IanMatthewHuff thanks for reporting, can you share the command-line being executed? I don't see one in the linked Issue.

@blink1073 the nbconvert example is because now that we fully adopt argparse, positional arguments must now be contiguous. This is why the code:

```python
nbconvertapp.main(["nbconvert", "--output", "hi", "Untitled.ipynb"])
```

is failing, because it only accepts the first occurrence of positional arguments (`nbconvert` and anything else before `--output`) and errors on the second (`Untitled.ipynb` and any after).

Whereas traitlets 4 found positional arguments anywhere, so it behaved equivalent to:

```python
nbconvertapp.main(["--output", "hi", "nbconvert", "Untitled.ipynb"])
# or
nbconvertapp.main(["nbconvert", "Untitled.ipynb", "--output", "hi"])
```

both of which produce the same output (including the warning about no notebooks matching `nbconvert`) with traitlets 4 and 5 and are equivalent to the original command in traitlets 4. The warning is because this command has requested to convert the notebooks `nbconvert` and `Untitled.ipynb`, but `nbconvert` doesn't exist. I assume this initial arg is added in error, assuming that `main(argv)` should be the same as `main(sys.argv)` (including the executable in item 0), while `main()` actually only expects arguments to be passed, not the executable path,e.g. `main(sys.argv[1:])`. The warning in nbconvert hid an error where there always should have been one, which is now raised in traitlets 5.

**Comment by minrk** [comment]
@IanMatthewHuff nvm, found the example and discussion on https://github.com/ipython/ipykernel/issues/543 . On the case! I know exactly what the issue is - incomplete backward-compatibility coverage for the old `_safe_literal_eval` in from_string for Bytes types.
