### ISSUE TITLE
Can't pass multiple ipython extensions via command line arguments

### ISSUE THREAD

**Issue by ashkop** [ipython/traitlets#614]
Since traitlets upgrade to 5.0.0 when I try to launch ipython with these command line options:
```
ipython --ext django_extensions.management.notebook_extension --ext my.custom.extension
```
It fails with error:
```
[TerminalIPythonApp] CRITICAL | Bad config encountered during initialization: Invalid argument: 'TerminalIPythonApp.extra_extension=DeferredConfigList(['django_extensions.management.notebook_extension', 'my.custom.extension
`'])'
```

It works fine on version 4.3.3. I'm not sure if that's a regression or new expected behavior. As you can see here https://django-extensions.readthedocs.io/en/latest/shell_plus.html#ipython-notebook `django-extensions` library expected it to work when you specify two `--ext` options.

**Comment by rmorshea** [comment]
Maybe related? https://github.com/ipython/traitlets/pull/441#issuecomment-323811638

**Comment by rmorshea** [comment]
Also maybe related? https://github.com/ipython/traitlets/issues/608#issuecomment-686964786

**Comment by minrk** [comment]
`--ext` never accepted multiple arguments. If you passed it multiple times, each time it would replace the previous value. With traitlets 5, you *can* specify options that accept multiple values, but the IPython [InteractiveShellApp.extra_extension](https://github.com/ipython/ipython/blob/aa2b54815c55c2f229de8c57e20a757d1b27ffd7/IPython/core/shellapp.py#L121-L123) option.

If IPython *required* traitlets 5, this could be easily fixed by changing the trait to `List(Unicode())`, in which case specifying `--ext` multiple times would do what is expected here. However, traitlets 4 doesn't know how to configure list traits on the command-line (this is one of the main new features in traitlets 5), so it would be tricky to do in a backward-compatible way.

The other fix, and one that we can consider on the traitlets side, is reconsider what we do when given multiple values for a scalar config (in this case Unicode). As it is now, we produce errors (it could be a better one!). This may be a good change because traitlets 4 behavior has led to the expectation illustrated here that multiple values are accepted when they are not. We could choose to match traitlets 4, though, and only preserve the last value. This is not uncommon behavior, seen relatively often in e.g. compiler flags, so I could be convinced either way.

**Comment by ashkop** [comment]
Thanks for the answer. I must say that it was quite confusing cause I just rebuilt the docker image, and suddenly it stopped working. The `django-extensions` docs didn't help, since they explicitly say that several `--ext` should work. Raising an error is more explicit and I like that, but it's not backwards compatible and some people might have a hard time figuring out what's wrong, like me.

Is there any other way to specify several extensions that I want to load? Or I guess I can have one extension that loads all other extensions?

**Comment by minrk** [comment]
> Is there any other way to specify several extensions that I want to load?

Yes! Config files can be used to load a list of extensions:

```python
# ~/.ipython/profile_default/ipython_config.py
c.InteractiveShellApp.extensions = ["myext1", "myext2", ...]
```

Or create a profile named `django` (or whatever you like) with this config:

```bash
ipython profile create django
cat > $(ipython profile locate django)/ipython_config.py <<EOF 
c.InteractiveShellApp.extensions = [
    "django_extensions.management.notebook_extension",
    "my.custom.extension",
]
EOF
ipython --profile django
```

This `extra_extension` singleton exists only to expose *one more extension* to load from the CLI, beyond the list in the config file. The only reason it's a singleton is that we couldn't handle multiple values yet. Now that traitlets 5 supports specifying multiple values on the CLI exactly as you've given here, we can add support for this in IPython, we'd just have to require traitlets 5 to do it.

**Comment by ashkop** [comment]
Great, thank you very much!

I think it would be better to support multiple values with `--ext` in future, should I open an issue in IPython for that?

**Comment by minrk** [comment]
>  should I open an issue in IPython for that?

Yes, please do!

**Comment by minrk** [comment]
> it's not backwards compatible and some people might have a hard time figuring out what's wrong, like me.

You're right! We can't make a change like this fully backward-compatible, but we are doing our best to balance keeping everything working with making things tractable as we improve them. So far, many of the incompatibilities are on cases like this one, where what has become incompatible *also didn't work*, so we've turned a silent failure to do what you asked into a loud failure to do what you asked :) While I recognize that it's still not great and we will always work to improve our error messages (#616 hopefully helps a bit).
