### ISSUE TITLE
traitlets does not work with python 3.6

### ISSUE THREAD

**Issue by didiercrunch** [ipython/traitlets#628]
Your library does not work with python 3.6.  It cause a failure of installing jupyter on python 3.6 .  Basically, every tutorial about jupyter are void because of this issue.  I am pretty sure you can live without format str.

**Comment by rmorshea** [comment]
See related: https://github.com/ipython/traitlets/issues/620

The Jupyter ecosystem follow's Numpy's [community policy standard](https://numpy.org/neps/nep-0029-deprecation_policy.html) for what Python versions to support or not support. Given the release date of Traitlets 5.0 it will only support Python 3.7 and above.

**Comment by didiercrunch** [comment]
Look, I cannot tell you what to do, but the fact is that many production system uses python 3.6.  Python 3.7 is **extremely** recent.  Personally, I use centos 7 and there is no python 3.7 there.  I consider myself lucky to not be stuck with python 3.4.

At least, if there were a possibility to install an old version of jupyter with `pip install jupyter==6.2.2` but no!  I tried everything to install an older version of jupyter and, because of dependency nightmare, I was always hitting a wall with traitlets.

In fine, I cloned traitlets, removed 5 or 6 format strings and installed it.  Then jupyter installed.


I can make a pull request if you want.

**Comment by minrk** [comment]
As mentioned in #620, if you have a relatively recent pip, you will not get the latest traitlets that has dropped support for old Pythons, you will get the latest version that *does*  support your Python. Dropping support does not mean that it stops working on old versions, it means that `pip install traitlets` will install 4.3.3 instead of 5.0.

As an example, running in a `python:3.6` docker container, `pip install jupyter` gets these packages:

<details>

```

pyparsing           2.4.7
pyrsistent          0.17.3
python-dateutil     2.8.1
pyzmq               19.0.2
qtconsole           4.7.7
QtPy                1.9.0
Send2Trash          1.5.0
setuptools          50.3.0
six                 1.15.0
terminado           0.9.1
testpath            0.4.4
tornado             6.0.4
traitlets           4.3.3
wcwidth             0.2.5
webencodings        0.5.1
wheel               0.35.1
widgetsnbextension  3.5.1
zipp                3.2.0
```
</details>

and `jupyter notebook` works just fine.

`pip install jupyter` continues to install working versions on Python 2.7, 3.5, or 3.6 because pip will ignore versions that do not support your version of Python. If you are getting traitlets 5 from pip, that means your pip is *several years* out of date. The firs thing to do is:

```bash
pip install --upgrade setuptools pip
```
