### ISSUE TITLE
Support for pickle and copy

### ISSUE THREAD

**Issue by NeilGirdhar** [ipython/traitlets#94]
Has there been any thought about supporting Python pickling and copying?  In other words, implementing `__setstate__` and `__getstate__` on the `Instance` type?

I did something like this:

``` python
class HasTraits:

    def __getstate__(self, **kwargs):
        state = super().__getstate__(**kwargs)

        # Create entries for traits that want to be pickled.
        for name, trait in self.class_traits(pickled=True).items():
            state[name] = trait.getstate(self, **kwargs)

        return state

    def __setstate__(self, state):
        # Set traits that were pickled.
        for name, trait in self.class_traits(pickled=True).items():
            value = state[name]
            trait.setstate(self, value)

        super().__setstate__(state)


class Instance(ClassBasedTraitType):

    def getstate(self, **kwargs):
        return trait.get(self, None)

    def setstate(self, obj, value):
        trait.set(self, value)
```

after which of course `pickle` and `copy` operations save and reload the state of traits automatically.

**Comment by rmorshea** [comment]
I don't have my computer available so I can't test it, but it seems like pickling for this is already supported since the trait values are stored in `_trait_values`.

**Comment by NeilGirdhar** [comment]
@rmorshea Oh of course, never mind…

**Comment by rmorshea** [comment]
I believe so, because if you decided to store them as `state[name]` in `__getstate__`, you would have to pop them off the state in `__setstate__` so that the values didn't remain on the `__dict__` of the `HasTraits` instance and thus obstruct the descriptors using `__set__` and `__get__`.

So in the example you gave above, everything should pickle fine, but the reloaded `HasTraits` instance would no longer be using its `TraitTypes` because all the values exist on the instance's `__dict__`, so there would never be no check for descriptors on the class.

**Comment by rmorshea** [comment]
^ deleted old comment (couldn't check to see if `__dict__` overrided descriptors since my computer's still out of commission). In any case though, going down the route of your example, you'd have to manage pickleability both on `state[name]` and `state['_trait_values'][name]`. However, checking for `getstate` and `setstate` methods that control the values in `state['_trait_values']` is probably worth considering.

**Comment by rmorshea** [comment]
@SylvainCorlay @jasongrout
Would it be worth including `getstate(self, obj)` and `setstate(self, obj, value)` methods for `TraitTypes` whose values are potentially unpicklable that get called in `__getstate__` and `__setstate__`?

**Comment by rmorshea** [comment]
I think we can close this until someone else requests TraitType specific get/setstate methods
